### ISSUE TITLE
How to change the hash from slide-1, etc

### ISSUE THREAD

**Issue by babyewok** [lukesnowden/magic-accordion#2]
I see that I can open a tab from an anchor link by using #slide-1, #slide-2, etc.  However, how can I get magic accordion to use the id of the h2 tag instead?

**Comment by lukesnowden** [comment]
custom hash's are not currently integrated im afraid as I didn't think this woudl be a big deal. For you to do this you would need to alter how the plugin gets the slide number from the hash (https://github.com/lukesnowden/magic-accordion/blob/master/jquery.magic-accordion.js#L331) and also how it updates the hash on click (https://github.com/lukesnowden/magic-accordion/blob/master/jquery.magic-accordion.js#L238)

**Comment by babyewok** [comment]
Hmm, OK.  Well on a slightly different note if I have the hashTrail set to true so that I open a panel with an anchor link, how can I also have a particular tab open, WITHOUT the hash being added to the url until a relevant link is clicked.   I don't mind what hash is added after the user has clicked on a few things, but I don't like the fact that in order to have a default tab open AND to be able to open a tab from a link, the hash is added to the url as soon as the page opens, so mywebsite.co.uk/ becomes mywebsite.co.uk/slide-1, which really isn't ideal.

**Comment by lukesnowden** [comment]
I think this is the option you are looking for https://github.com/lukesnowden/magic-accordion/blob/master/jquery.magic-accordion.js#L20

**Comment by babyewok** [comment]
Actually, I can link to a panel without hashTrail, and therefore can have a panel open by default without the hash being added to the url, BUT if I was to close all panels and then click on my anchor link, it won't work.  It only works when a panel is already open.  Is there a work around for that at all, just in case someone was to close all panels then try one of the (internal) anchor links?

**Comment by lukesnowden** [comment]
I would open that up as a new issue. seems like there maybe some fault here: https://github.com/lukesnowden/magic-accordion/blob/master/jquery.magic-accordion.js#L373

**Comment by babyewok** [comment]
Actually, I may have figured a way around it.... I am using jQuery scrollTo to get around the repositioning of the accordion to the top when a new one is opened and I think I can also solve this with scrollTo as well.
